services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - neuro_net
    depends_on:
      - backend
    restart: unless-stopped
    mem_limit: 128m

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      neuro_net:
        aliases:
          - backend
    restart: unless-stopped
    mem_limit: 512m
    environment:
      - PYTHONUNBUFFERED=1

networks:
  neuro_net:
    name: neuro_net
    driver: bridge
